---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: devwatt-pipelines
  - name: bosh-director-config
  - name: postgres-release

run:
  path: devwatt-pipelines/ci/postgres-upgrade/upgrade-postgres/scripts/upgrade-postgres.sh