- type: replace
  path: /releases/name=percona-mongodb-exporter?
  value:
    name: percona-mongodb-exporter
    version: latest

- type: replace
  path: /instance_groups/name=grafana/jobs/name=percona_dashboards?
  value:
    name: percona_dashboards
    release: percona-mongodb-exporter

- type: replace
  path: /instance_groups/name=alertmanager/vm_type
  value: medium
- type: replace
  path: /instance_groups/name=alertmanager/networks/name=default/name
  value: prometheus

- type: replace
  path: /instance_groups/name=prometheus2/vm_type
  value: medium
- type: replace
  path: /instance_groups/name=prometheus2/networks/name=default/name
  value: prometheus
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/mysql_alerts/*.alerts.yml
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/shield_alerts/*.alerts.yml
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/rule_files/-
  value: /var/vcap/jobs/elasticsearch_alerts/*.alerts.yml
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=mysql_alerts?
  value: 
    name: mysql_alerts
    release: prometheus


- type: replace
  path: /instance_groups/name=database/vm_type
  value: medium
- type: replace
  path: /instance_groups/name=database/networks/name=default/name
  value: prometheus
 
- type: replace
  path: /instance_groups/name=grafana/vm_type
  value: medium
- type: replace
  path: /instance_groups/name=grafana/networks/name=default/name
  value: prometheus
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=MySQL?
  value:
    name: MySQL
    files: [ /var/vcap/jobs/mysql_dashboards/*.json ]
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=MongoDB?
  value:
    name: MongoDB
    files: [ /var/vcap/jobs/percona_dashboards/MongoDB*.json ]    
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=System?
  value: 
    name: System
    files: [ /var/vcap/jobs/system_dashboards/*.json]
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=ElasticSearch?
  value: 
    name: ElasticSearch
    files: [ /var/vcap/jobs/elasticsearch_dashboards/*.json ]
- type: replace
  path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/prometheus/dashboard_folders/name=Shield?
  value: 
    name: Shield
    files: [ /var/vcap/jobs/shield_dashboards/*.json ]
- type: replace
  path: /instance_groups/name=grafana/jobs/name=mysql_dashboards?
  value:
    name: mysql_dashboards
    release: prometheus
- type: replace
  path: /instance_groups/name=grafana/jobs/name=system_dashboards?
  value:
    name: system_dashboards
    release: prometheus
- type: replace
  path: /instance_groups/name=grafana/jobs/name=elasticsearch_dashboards?
  value:
    name: elasticsearch_dashboards
    release: prometheus
- type: replace
  path: /instance_groups/name=grafana/jobs/name=shield_dashboards?
  value:
    name: shield_dashboards
    release: prometheus

- type: replace
  path: /instance_groups/name=nginx/vm_type
  value: small
- type: replace
  path: /instance_groups/name=nginx/networks/name=default/name
  value: prometheus


#- type: replace
  #path: /instance_groups/name=concourse/jobs/name=groundcrew/properties/https_proxy_url?
  #value: http://10.165.0.139:3128
#- type: remove
#  path: /instance_groups/name=concourse/networks/name=((network_name))/static_ips
