---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: devwatt-pipelines

outputs:
  - name: bosh-director-config

run:
  path: devwatt-pipelines/ci/common/scripts/create-bosh-config.sh