---
resource_types:
- name: email
  type: docker-image
  source:
    repository: pcfseceng/email-resource

resources:


  - name: prometheus-release
    type: github-release
    source:
      owner: bosh-prometheus
      repository: prometheus-boshrelease

  - name: prometheus-release-src
    type: git
    source:
      #uri:    https://github.com/bosh-prometheus/prometheus-boshrelease.git
      uri: ((repositories.prometheus.uri))
      #branch: master
      branch: ((repositories.prometheus.branch))
      username: ((repositories.prometheus.username))
      password: ((repositories.prometheus.password))  

  - name: devwatt-pipelines
    type: git
    source:
      uri:    ((repositories.devwatt-ci.uri))
      branch: ((repositories.devwatt-ci.branch))
      username: ((repositories.devwatt-ci.username))
      password: ((repositories.devwatt-ci.password))

  - name: send-email
    type: email
    source:
      smtp:
        host: ((mail.host))
        port: ((mail.port)) # this must be a string
        anonymous: true
        skip_ssl_validation: true
      from: concourse@dbsp.dw
      to: ((mail.to))

jobs:

- name: upgrade-prometheus
  plan:

    - get: devwatt-pipelines

    - aggregate:
      - get: prometheus-release
        trigger: true

      - get: prometheus-release-src


      - task: create-bosh-config
        file: devwatt-pipelines/ci/common/tasks/create-bosh-config.yml
        params:
          CA_CERT:  ((bosh-server.ca))
          IP:       ((bosh-server.ip))
          ALIAS:    ((bosh-server.alias)) 
          USER:     ((bosh-server.user))
          PASSWORD: ((bosh-server.password))  

    - task: upgrade-prometheus
      file: devwatt-pipelines/ci/prometheus-upgrade/upgrade-prometheus/tasks/upgrade-prometheus.yml
      params:
          ALIAS:                            ((bosh-server.alias))
          UAA_BOSH_EXPORTER_CLIENT_SECRET:  ((bosh-server.uaa_bosh_exporter_client_secret))
          IP:                               ((bosh-server.ip))
          METRICS_ENVIRONMENT:              ((prometheus.metrics-environment))
      on_success:  
        put: send-email
        params:
          subject_text: "[Devwatt DBSP] ${BUILD_PIPELINE_NAME} Succeed"
          body_text: "Upgrade Succeed: ${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"
      on_failure:
        put: send-email
        params:
          subject_text: "[Devwatt DBSP] ${BUILD_PIPELINE_NAME} Failed!!"
          body_text: "Upgrade failed: ${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}"