---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/bosh-cli
    tag: latest

inputs:
  - name: devwatt-pipelines
  - name: bosh-director-config
  - name: garden-release

run:
  path: devwatt-pipelines/ci/garden-runc-upgrade/upgrade-garden/scripts/upgrade-garden.sh